#!/bin/bash

export NVM_DIR="/home/ec2-user/.nvm" 
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

cd /home/ec2-user/CMPE-273-Team-Project-Quora/backend
npm install

cd /home/ec2-user/CMPE-273-Team-Project-Quora/kakfa
npm install
