#!/bin/bash

export NVM_DIR="/home/ec2-user/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

cd /home/ec2-user/CMPE-273-Team-Project-Quora/backend && pm2 start index.js
cd /home/ec2-user/CMPE-273-Team-Project-Quora/kakfa/server && pm2 start server.js
